### ISSUE TITLE
Throw an error if the user tries to parse an OpenAPI 3 document

### ISSUE THREAD

**Issue by ffflorian** [welovecoding/swaxios#242]

**Comment by bennycode** [comment]
OpenAPI 3 documents have the following property in their JSON schema:

> {"openapi":"3.0.0", ...}

Parsing the "openapi" property will help to detect if it is version 3 or below.

**Comment by bennycode** [comment]
Swagger documents don't have the "openapi" property. Instead those have markers like `"swagger": "2.0"`. That's why checking for the pure existence of the "openapi" property is good enough.

I made a PR for that: https://github.com/welovecoding/swaxios/pull/273
